---
title: "探討地震與海洋之間的關係"
author: Jason Hsu
date: "6/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### 研究動機
<p>
我們居住的台灣，颱風與地震是兩大天然災害，曾經閱讀過一些資料，其中提到若較少的颱風數量，可以進一步推論當年度可能有較大的地震發生，從簡單的比較來看，1999年的921大地震，芮氏規模達到7.3，而當年的颱風數量僅有3個；而2001年的納莉颱風帶走了94條生命與龐大的財產損失，但地殼運動卻相對平靜。從地震與颱風的關聯來看，颱風的生成與海洋有很大的關係，因此給我了這個想法，what if 地震與海洋有關聯性呢？
</p><a href="http://www.epochtimes.com/b5/12/9/8/n3678237.htm" title="參考資料">參考資料</a>

-----

### 資料介紹
- 地震資料：採用中央氣象局氣象資料開放平臺中的"地震目錄-歷史地震目錄"
  - <a href="https://opendata.cwb.gov.tw/dataset/earthquake/E-A0073-002" title="連結">連結</a>
  - 格式：XML
  - 描述：臺灣地震觀測網之地震目錄-提供1900年起至前1年度之歷史地震目錄，每年1個xml，以ZIP格式壓縮提供
  - 資料欄位：發震時間、震央位置、震源深度、芮氏規模、定位測站個數、定位相位個數、震央距、最大空餘角度、震波走時殘差、標準偏差、定位品質
- 海水平面：採用中央氣象局氣象資料開放平臺中的"海平面統計-臺灣各地潮位觀測月平均海平面"
  - <a href="https://opendata.cwb.gov.tw/dataset/forecast/C-B0048-001" title="連結">連結</a>
  - 格式：JSON
  - 描述：臺灣各地潮位觀測月平均海平面-
  - 資料欄位：測站名稱、測站代碼、西元年月、平均潮位、最高高潮位、最低低潮位
- 海水溫度：採用中央氣象局氣象資料開放平臺中的"海溫統計-臺灣海域各地海溫觀測月統計"
  - <a href="https://opendata.cwb.gov.tw/dataset/forecast/C-B0050-001" title="連結">連結</a>
  - 格式：JSON
  - 描述：臺灣海域各地海溫觀測月統計-臺灣海域各地海溫觀測月統計
  - 資料欄位：測站名稱、測站代碼、經緯度、西元年月、月均溫(°C)、月最高溫(°C)、月最高溫發生時間、月最低溫(°C)、月最低溫發生時間
- 颱風資料：採用中央氣象局颱風資料庫中的"有發警報颱風列表"
  - <a href="https://rdc28.cwb.gov.tw/TDB/public/warning_typhoon_list/" title="連結">連結</a>
  - 格式：Web Table
  - 描述：有發警報颱風列表
  - 資料欄位：年份、颱風編號、颱風名稱、侵臺路徑分類、警報期間、近臺強度、近臺最低氣壓(hPa)、近臺最大風速(m/s)、近臺7級風暴風半徑(km)、近臺10級風暴風半徑(km)、警報發布報數


### 分析議題
#### 假設
- 假設一、海水平面與地震深度有關聯
- 
#### 分析結果


### 結論
### 心得
首先要先感謝老師開了這門特別的課程，我覺得R語言對於資料表的處理與分析非常容易上手，讓我有點愛上它！在課程方面老師用心的寫了 gitbook，對於學習R非常有幫助。這次的期末報告雖然很不幸的只有自己一人，減少了許多溝通成本，卻也相對地增加了不少負擔。打從一開始在思考題目的時候，大致上就只朝著自然環境的方向，

#### Source Code
You can download the source from github repo : <a href="https://github.com/jason19970210/BigDataAnalyticalMethods/tree/master/Final">link</a>